apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: poc-backstage-from-aws 
  description: A description for teste
  owner: team-a
spec:
  type: service
  lifecycle: production
  owner: team-a
